{
 "title": "JAAS Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentile", "query": "50, 75, 85, 90, 95" }
  ]
 },
 "panels": [
  { "title": "JIMM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jimm_websocket_concurrent_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Managed Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jimm_system_controller", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Managed Models",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller) (jimm_system_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{juju_charm=~\"juju-jimm-k8s|jimm\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Memory Usage Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{juju_charm=~\"juju-jimm-k8s|jimm\"}[$__rate_interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Running Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "go_goroutines{juju_charm=~\"juju-jimm-k8s|jimm\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{juju_charm=~\"juju-jimm-k8s|jimm\"}[$__rate_interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Freed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{juju_charm=~\"juju-jimm-k8s|jimm\"}[$__rate_interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "description": "Only the 75 percentile and maximum GC time are shown per unit.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{juju_charm=~\"juju-jimm-k8s|jimm\", quantile=~\"0.75|1\"}",
     "legendFormat": "{{juju_unit}} p{{quantile}}"
    }
   ]
  },
  { "title": "Juju Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Ping Duration Per Controller (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.${percentile}, sum by(le, controller) (rate(jimm_juju_ping_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juju Error Rate By Controller & Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(controller, method) (rate(jimm_juju_error_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juju Call Durations Per Controller (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.${percentile}, sum by(le, controller) (rate(jimm_juju_call_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juju Call Rate Per Controller",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(controller) (rate(jimm_juju_call_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juju Call Durations Per Method (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.${percentile}, sum by(le, method) (rate(jimm_juju_call_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Juju Call Rate Per Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by(method) (rate(jimm_juju_call_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Auth Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(method) (rate(jimm_auth_failure_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Vault Call Durations (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "histogram_quantile(0.${percentile}, sum by(le, method) (rate(jimm_vault_call_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by(method) (rate(jimm_vault_call_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OpenFGA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "OpenFGA Call Durations (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "histogram_quantile(0.${percentile}, sum by(le, method) (rate(jimm_openfga_call_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenFGA Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by(method) (rate(jimm_openfga_call_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "DB Calls Duration (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "histogram_quantile(0.${percentile}, sum by(le, method) (rate(jimm_db_query_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum by(method) (rate(jimm_db_query_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}