name: Charm Build
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-charm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: sudo snap install charmcraft --channel=2.x/stable --classic
      - run: sudo charmcraft pack --destructive-mode --verbosity=trace
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: jimm-k8s-charm
          path: ./*.charm
          if-no-files-found: error
