name: Charm Build
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-charm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: git fetch --prune 
      - run: sudo snap install charmcraft --channel=2.x/stable --classic
      - run: sudo charmcraft pack --destructive-mode --verbosity=trace
      - uses: actions/upload-artifact@v4
        with:
          name: jimm-k8s-charm
          path: ./*.charm
          if-no-files-found: error
