name: Charm Build
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-charm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: sudo snap install charmcraft --channel=2.x/stable --classic
      - run: sudo charmcraft pack --destructive-mode --verbosity=trace
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: jimm-k8s-charm
          path: ./*.charm
          if-no-files-found: error
